# Generated by Django 4.2.2 on 2023-09-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='tran_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
