# Generated by Django 4.2.2 on 2023-08-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_bankaccount_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='transaction',
        ),
    ]
